### ISSUE TITLE
Branch variable not being passed correctly

### ISSUE THREAD

**Issue by wavemoran** [promiseofcake/circleci-trigger-action#20]
I'm trying to use this action to trigger a CircleCI workflow. I'm setting up things like the sample in the README, however I keep getting 400 errors from CircleCI with the message

```
data: { message: 'Branch not found' }
```

I _think_ it's because the environment variable in the `branch` config isn't getting converted correctly.

Here's my relevant workflow config:

```
with:
    user-token: ${{ secrets.CIRCLECI_TOKEN }}
    project-slug: foo/bar
    branch: ${GITHUB_REF#refs/heads/}
    payload: '{"demo_deploy_workflow": true}'
```

and relevant logs:

```
Run promiseofcake/circleci-trigger-action@v1
  with:
    user-token: ***
    project-slug: foo/bar
    branch: ${GITHUB_REF#refs/heads/}
    payload: {"demo_deploy_workflow": true}
HTTP Error:  Error: Request failed with status code 400
    at createError (/home/runner/work/_actions/promiseofcake/circleci-trigger-action/v1/node_modules/axios/lib/core/createError.js:16:1)
    at settle (/home/runner/work/_actions/promiseofcake/circleci-trigger-action/v1/node_modules/axios/lib/core/settle.js:17:1)
    at IncomingMessage.handleStreamEnd (/home/runner/work/_actions/promiseofcake/circleci-trigger-action/v1/node_modules/axios/lib/adapters/http.js:236:1)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1184:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  config: {
    url: 'https://circleci.com/api/v2/project/gh/foo/bar/pipeline',
    method: 'post',
    data: '{"branch":"${GITHUB_REF#refs/heads/}","parameters":{"demo_deploy_workflow":true}}',
```

Does the branch environment variable need to be in a different format?

**Comment by promiseofcake** [comment]
I found that in order to do the interpolation, I needed to set the branch name as an environment variable in a pre-step. So it would look something like this: 

```yaml
- name: Capture triggering branch name
  run: echo "::set-env name=BRANCH_NAME::${GITHUB_REF#refs/heads/}"
- name: Trigger CircleCI build-alpha workflow.
  uses: ./.github/actions/vsco/circleci-trigger-action
  with:
    branch: ${{ env.BRANCH_NAME }}
```
